name: Setup MySQL and Create Database

on:
  workflow_run:
    workflows: ["SQL Syntax Check"]
    types:
      - completed

jobs:
  setup-mysql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install MySQL
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server mysql-client

      - name: Start MySQL Service
        run: |
          sudo systemctl start mysql
          sudo systemctl status mysql || true  # Debugging

      - name: Lint and Fix SQL Formatting
        run: |
          pip install sqlfluff
          sqlfluff fix DatabaseAdministration/Testing_workflow --dialect mysql --force

      - name: Verify Fixed SQL Files
        run: |
          git diff -- DatabaseAdministration/Testing_workflow/*.sql || echo "No changes needed."

      - name: Commit Changes (Optional)
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add DatabaseAdministration/Testing_workflow/*.sql
          git commit -m "Auto-formatted SQL files with SQLFluff" || echo "No changes to commit."
          git push || echo "No changes to push."

      - name: Create Database
        run: |
          sudo mysql --user=root --password=root -e "CREATE DATABASE IF NOT EXISTS my_local_db;"
          sudo mysql --user=root --password=root -e "SHOW DATABASES;"

      - name: Run SQL Scripts
        run: |
          for file in DatabaseAdministration/Testing_workflow/*.sql; do
            echo "Running SQL script: $file"
            sudo mysql --user=root --password=root my_local_db < "$file"
          done

      - name: Verify Database Exists
        run: |
          sudo mysql --user=root --password=root -e "SHOW DATABASES;"
