name: AutoTest Database Automation

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main

jobs:
  install-sql-client:
    name: Install SQL Server Client
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SQL Server Client
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          sudo curl -o /etc/apt/sources.list.d/mssql-release.list https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/mssql-server-2019.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

  create-database:
    name: Connect and Create Database
    runs-on: ubuntu-latest
    needs: install-sql-client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Database
        env:
          PINGGY_URL: ${{ secrets.PINGGY_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sqlcmd -S "$PINGGY_URL" -U Auto_user -P "$DB_PASSWORD" -Q "CREATE DATABASE AutoTestdb;"

  create-user-table:
    name: Create User Table
    runs-on: ubuntu-latest
    needs: create-database
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Table
        env:
          PINGGY_URL: ${{ secrets.PINGGY_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sqlcmd -S "$PINGGY_URL" -U Auto_user -P "$DB_PASSWORD" -d AutoTestdb -Q "
          CREATE TABLE [dbo].[user] (
              ID INT IDENTITY(1,1) PRIMARY KEY,
              Name NVARCHAR(50),
              Surname NVARCHAR(50),
              Email NVARCHAR(100) UNIQUE
          );"

  create-stored-procedure:
    name: Create Stored Procedure
    runs-on: ubuntu-latest
    needs: create-user-table
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create Procedure
        env:
          PINGGY_URL: ${{ secrets.PINGGY_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sqlcmd -S "$PINGGY_URL" -U Auto_user -P "$DB_PASSWORD" -d AutoTestdb -Q "
          CREATE PROCEDURE InsertUserData
              @Name NVARCHAR(50),
              @Surname NVARCHAR(50),
              @Email NVARCHAR(100)
          AS
          BEGIN
              INSERT INTO [dbo].[user] (Name, Surname, Email)
              VALUES (@Name, @Surname, @Email);
          END;"

  insert-sample-data:
    name: Insert Sample Data
    runs-on: ubuntu-latest
    needs: create-stored-procedure
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Insert Data
        env:
          PINGGY_URL: ${{ secrets.PINGGY_URL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          sqlcmd -S "$PINGGY_URL" -U Auto_user -P "$DB_PASSWORD" -d AutoTestdb -Q "
          EXEC InsertUserData 'John', 'Doe', 'john.doe@example.com';"
