name: AutoTest Database Automation

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  setup-sql-environment:
    name: Setup SQL Server Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install SQL Server Client
        run: |
          # Update package list
          sudo apt-get update
          
          # Install prerequisites
          sudo apt-get install -y curl gnupg unixodbc-dev
          
          # Clean up any existing Microsoft repository configurations and keys
          sudo rm -f /etc/apt/sources.list.d/mssql-release.list
          sudo rm -f /etc/apt/sources.list.d/microsoft-prod.list
          sudo rm -f /usr/share/keyrings/microsoft-prod.gpg
          sudo rm -f /usr/share/keyrings/microsoft-archive-keyring.gpg
          
          # Add Microsoft GPG key
          curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /usr/share/keyrings/microsoft-archive-keyring.gpg > /dev/null
          
          # Add repository for Ubuntu 24.04
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/ubuntu/24.04/prod noble main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
          
          # Update package list again and install SQL Server tools
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
          
          # Add sqlcmd to PATH
          echo "/opt/mssql-tools18/bin" >> $GITHUB_PATH

      - name: Test Database Connection
        env:
          PINGGY_HOST: ${{ secrets.PINGGY_HOST }}
          PINGGY_PORT: ${{ secrets.PINGGY_PORT }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SQL_USER: ${{ secrets.SQL_USER }}
        run: |
          # Test connection
          echo "Testing database connection..."
          sqlcmd -S "$PINGGY_HOST,$PINGGY_PORT" -U "$SQL_USER" -P "$DB_PASSWORD" -Q "SELECT 1" -N -C -b -o connect.log
          if [ $? -ne 0 ]; then
            echo "::error::Connection test failed!"
            cat connect.log
            exit 1
          fi
          echo "✅ Connection test successful!"
          cat connect.log

      - name: Setup Database
        env:
          PINGGY_HOST: "rnonc-41-145-197-133.a.free.pinggy.link"
          PINGGY_PORT: "45297"
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SQL_USER: ${{ secrets.SQL_USER }}
        run: |
          # Execute setup script with detailed error output
          echo "Running database setup script..."
          set +e  # Temporarily disable exit-on-error to capture output
          sqlcmd -S "$PINGGY_HOST,$PINGGY_PORT" -U "$SQL_USER" -P "$DB_PASSWORD" \
            -N -C \
            -i "./DatabaseAdministration/SQLStatements/SetupDatabase.sql" \
            -b -o output.log -e -V 16 -y 1000
          EXIT_CODE=$?
          set -e  # Re-enable exit-on-error
          
          # Check execution result
          if [ $EXIT_CODE -eq 0 ]; then
            echo "✅ Database setup completed successfully!"
            cat output.log
          else
            echo "::error::Database setup failed with exit code $EXIT_CODE"
            cat output.log
            exit 1
          fi
