name: AutoTest Database Automation

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest  # Runs on Ubuntu

    env:
      CONNECTION_STRING: "Server=SAMBE2025018;Database=AutoTestDB;User Id=github_user1;Password=StrongPassword;TrustServerCertificate=true"  # Hardcoded connection string

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Pulls the latest code

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'  # Using .NET 8

      - name: Restore Dependencies
        working-directory: DatabaseAdministration/Project/SqlServerApi
        run: dotnet restore  # Restores dependencies

      - name: Build API
        working-directory: DatabaseAdministration/Project/SqlServerApi
        run: dotnet build --no-restore  # Builds the project

      - name: List Working Directory
        working-directory: DatabaseAdministration/Project/SqlServerApi
        run: ls -la  # List files to verify the working directory

      - name: Run API (Foreground)
        working-directory: DatabaseAdministration/Project/SqlServerApi
        run: dotnet watch run  # Run API in the foreground to see logs

      - name: Install ngrok
        run: |
          curl -s https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
          unzip ngrok.zip
          rm ngrok.zip
          chmod +x ngrok
          ./ngrok authtoken YOUR_NGROK_AUTHTOKEN  # Replace with your ngrok authtoken

      - name: Start ngrok
        run: |
          nohup ./ngrok http 5085 > ngrok.log 2>&1 &

      - name: Verify API is Running
        run: |
          sleep 30  # Wait longer for the API to fully start
          curl -X GET "http://localhost:5085/api/database" || exit 1

      - name: Insert Sample User
        run: |
          curl -X POST "http://localhost:5085/api/database" \
            -H "Content-Type: application/json" \
            -d '{"name":"John","surname":"Doe","email":"john@example.com"}' || exit 1

      - name: Stop API and ngrok
        run: |
          pkill -f "dotnet run"
          pkill -f "ngrok http"
